### ISSUE TITLE
Bug in htp_mpart_part_handle_data - stack corruption

### ISSUE THREAD

**Issue by dbardbar** [OISF/libhtp#107]
In htp_mpart_part_handle_data(), there are these lines:

char buf[255];
strncpy(buf, part->parser->extract_dir, 254);
strncat(buf, "/libhtp-multipart-file-XXXXXX", 254 - strlen(buf));

If part->parser->extract_dir is longer than 254 chars, buf will not have a NULL terminator after strncpy.
Then strncat may write the additional "/libhtp-multipart-file-XXXXXX" string outside the buffer.

I suggest replacing with something like
snprintf(buf, sizeof(buf), "%s//libhtp-multipart-file-XXXXXX", part->parser->extract_dir);

Note that to be completely correct, the code above also needs to check the return value to make sure snprintf succeeded. Also, not sure if you support compiling with pre-C99.

**Comment by catenacyber** [comment]
Is this still an issue ?

**Comment by dbardbar** [comment]
I must say I can't recall what this is about. 7 years have passed...
But looking at the code as it is now, it seems that the code hasn't changed, so probably still a problem.

**Comment by catenacyber** [comment]
Thanks for the reply.
How are you using libhtp ? For Suricata ? (Suricata does not use this part of libhtp)

**Comment by dbardbar** [comment]
As I've said, I really can't recall why I opened this bug, in what context I saw it, did it impact any product I've worked with, or any other useful information.
The name Suricata vaguely rings a bell, but that's all I can say.

**Comment by catenacyber** [comment]
Thanks so closing, as multipart is handled by Suricata itself
