### ISSUE TITLE
version check fails with suricata 3.1.3

### ISSUE THREAD

**Issue by oxitech239** [OISF/libhtp#146]
For some foggy reason the libhtp version is not aligned with the version suricata is validating by means of the PKG_CHECK_MODULES macro. It appears the version derived from htp_version.h is written as 

> LibHTP v0.6.x

 
while suricata appears to expect a notation such as 0.6.x or rather 0.5

**Comment by inliniac** [comment]
Suricata works with the 0.5.x branch.

**Comment by oxitech239** [comment]
Sorry, it does not. It fails to detect the correct version. Tried 0.6.x 0.5.x 0.5.20. Suricate keeps on reporting it is not the correct version installed. 

Double checked the version installed in /usr/local/include/htp/htp_version.h
