### ISSUE TITLE
underscore in htp_validate_hostname

### ISSUE THREAD

**Issue by opoplawski** [OISF/libhtp#149]
According to the comment in htp_validate_hostname, "_" is allowed, but the code does not appear to do so:
```
            // According to the RFC, the underscore is not allowed in a label, but
            // we allow it here because we think it's often seen in practice.
            if (!(((c >= 'a') && (c <= 'z')) || ((c >= 'A') && (c <= 'Z')) || ((c >= '0') && (c <= '9')) || (c == '-'))) {
                return 0;
            }
```
We do see "_" in the wild, leading to suricata "HTTP Host header invalid" alerts.  I'm also happy with not allowing underscores, as they are invalid, but then the comment should go.

**Comment by inliniac** [comment]
Fixed in #155 by allowing the underscore.
