### ISSUE TITLE
Use dynamic in_line and out_line buffers to reduce per-connection memory consumption

### ISSUE THREAD

**Issue by ivanr** [OISF/libhtp#15]
At the moment, the HTTP connection parser will allocate two buffers of HTP_HEADER_LIMIT_HARD each (18,000 bytes), which means that we use at least 36 KB per connection. The buffer size _is_ configurable (via the field_limit_hard configuration option), but we should nevertheless investigate using buffers that grow on demand. Most request and response lines are nowhere near 18 KB.

**Comment by calfeld-zz** [comment]
Analysis of response data indicates that a length of 63 will catch 90% of all response header lines, 134 will catch 99%, 431 will catch 99.9%, and 878 will catch 99.99%.

As an aside, the largest response header line I found was 7819 bytes.

**Comment by calfeld-zz** [comment]
Analysis of _darkspace_ request data indicates that a length of 69 will catch 90% of all request header lines (and request line), 213 will catch 99%, 1291 will catch 99.9%, and 5404 will catch 99.99%.

The largest request line was 47,446 bytes.

**Comment by ivanr** [comment]
Closing, because I don't think that reducing the size of the line buffers is the way to go. We should optimize for the most common use case and eliminate buffers wherever possible.
