### ISSUE TITLE
libhtp crash at  deal multiple  decompression

### ISSUE THREAD

**Issue by qiangbei** [OISF/libhtp#158]
1、the  dump info 
(htp_connp_res_data+0xac)[0x1044fcc]
(htp_tx_state_response_headers+0x3ef)[0x1047a7f]
free(): invalid pointer: 0x000000000c09b468 ***

2、the analysis
when  use ixia to test the suricata who used libhtp, we find that the suricata crash.
for the strike is too much(8000), I don't kown which strike made it.
so by watch the dump info ,we find the the crash at htp_tx_state_response_headers.
then we add stub ,find the error at 
```
                    if (tx->connp->out_decompressor == NULL) {
                            free(input); // **the free will lead crash**
                            return HTP_ERROR;
                        }
```
the code  ` free`  exception handling used not good.

3、 solution  (I verified the change , and the suricata do not crash now !)

romove the the free like this :
  ```
                    if (tx->connp->out_decompressor == NULL) {
                            //free(input);
                            return HTP_ERROR;
                        }
                        tx->connp->out_decompressor->callback = htp_tx_res_process_body_data_decompressor_callback;
                        comp = tx->connp->out_decompressor;
                    } else {
                        comp->next = htp_gzip_decompressor_create(tx->connp, cetype);
                        if (comp->next == NULL) {
                            //free(input);
                            return HTP_ERROR;
                        }
```

thanks !

**Comment by victorjulien** [comment]
Fixed in #166, thanks!
