### ISSUE TITLE
Folded header field can be parsed as separate if there are no data available to peek into

### ISSUE THREAD

**Issue by i-rinat** [OISF/libhtp#159]
Here: https://github.com/OISF/libhtp/blob/546a99f3f0a7bf10cc4f0e7ad45c1db5ad3215e6/htp/htp_request.c#L665 a call to `IN_PEEK_NEXT()` is made in hope that it will look into the next character. However, if currently available data ends exactly after `\r\n`, there is nothing to look at. Macro `IN_PEEK_NEXT()` puts `-1` into `->in_next_byte` in that case.

Nothing wrong so far. But then `htp_is_folding_char(connp->in_next_byte)` is called. And as it doesn't expect `-1`, it treats `-1` as another character. Which is definitely is not an LWS. So if there is another folded line after the current buffer, it will be parsed as a normal field, not as a continuation of a previous line.

The easiest way to reproduce the issue is to feed libhtp one byte at a time. It's required for the request feeded to have a folded field spanning over three lines.

**Comment by victorjulien** [comment]
Fixed in #166, thanks!
