### ISSUE TITLE
README build instructions omit autoreconf

### ISSUE THREAD

**Issue by pilcrow** [OISF/libhtp#16]
Attempting to RPM-ify both 0.2.x branch (0.2.6) and master (46c41074) , noticed README refers to `./configure` which does not exist in source distribution.  Instead, `autoreconf -i` is needed, and then the README instructions are accurate.

**Comment by b1v1r** [comment]
The README is meant for the packaged version of libhtp source, which _should_ have configure already built.  There needs to be another doc for packagers and anyone else pulling from the repo vs pulling a source package.

**Comment by ivanr** [comment]
As far as I was able to determine, the README file did include the instructions for those working directly with the repository. However, there was a typo, and autoconf was specified instead of autoreconf. This is now fixed.
