### ISSUE TITLE
Clean up response line vars if htp_treat_response_line_as_body

### ISSUE THREAD

**Issue by rlmaers** [OISF/libhtp#160]
The function htp_connp_RES_LINE checks if the response line is valid or if it should be treated as body in case we're missing parts of the stream. However, if the htp_treat_response_line_as_body function returns one, then the old values in tx->response_line, tx->response_protocol, tx->response_status and tx->response_message remain. This results invalid output in Suricata.

**Comment by victorjulien** [comment]
Closing as #161 was merged. Thanks!
