### ISSUE TITLE
Spurious executable permissions on *.c and *.h files

### ISSUE THREAD

**Issue by bochecha** [OISF/libhtp#17]
Some of the source and header files have the executable bits set.

I'm trying to package libhtp for Fedora, and rpmlint (rightfully) complains about it so I'm running the following in the spec file:
`$ find . -name '*.c' -exec chmod -x '{}' \;
$ find . -name '*.h' -exec chmod -x '{}' \;`

Since Git can keep track of mode changes, it would be nice if you could commit such a change so that every distro packager doesn't have to do it in their own packages. :)

**Comment by wmetcalf** [comment]
resolved in 

https://github.com/ironbee/libhtp/commit/b27cbf187a0fa0f98e8955f5370c3712f9e8461d
