### ISSUE TITLE
Wrong end-of-line encoding for COPYING

### ISSUE THREAD

**Issue by bochecha** [OISF/libhtp#18]
I'm packaging libhtp for Fedora, and rpmlint is complaining that the end of line character is invalid, as it is CRLF (the Windows one) rather than just LF.

It's of course completely harmless, but since it's absolutely trivial and given that libhtp seems to be targetted at UNIX-like OSes (at least that's what the OS detection in configure.ac seems to indicate), it would make sense to fix it.

At the moment, I simply run the following in my spec file:
`$ dos2unix COPYING`

**Comment by wmetcalf** [comment]
resolved in

https://github.com/ironbee/libhtp/commit/b27cbf187a0fa0f98e8955f5370c3712f9e8461d
