### ISSUE TITLE
Remove header line copying

### ISSUE THREAD

**Issue by ivanr** [OISF/libhtp#26]
At the moment we copy individual header lines. We do not have strong use cases that require this functionality (the original motivation was to preserve raw data for forensic purposes), yet this feature significantly decreases performance and increases memory consumption. The one use case we do have is Suricata wanting to inspect raw request headers, but we implement it in a backward way, reassembling individual header lines back into a buffer.

In virtually all cases all request headers will be available to us in a single buffer. Once we identify the beginning and the end of request headers, we can just pass that same buffer to Suricata. We will still have to buffer when request headers arrive in pieces, but that happens only rarely.

To remove header line copying will mean to re-implement header parsing.

**Comment by inliniac** [comment]
Make sense. For the raw buffer in Suricata we will also need the newlines as they appear on the wire. 0x0d 0x0a normally, but sometimes it's just 0x0d (iirc). We have some signatures that want to know this to find poorly done malware.

**Comment by ivanr** [comment]
Removing enhancements from the issue tracker.

**Comment by ivanr** [comment]
Fixed in master.
