### ISSUE TITLE
Build failure on FreeBSD

### ISSUE THREAD

**Issue by wxsBSD** [OISF/libhtp#32]
Trying to build the tip of master on FreeBSD 9.0 results in:

cc1: warnings being treated as errors
htp_content_handlers.c: In function 'htp_ch_urlencoded_callback_request_body_data':
htp_content_handlers.c:67: warning: dereferencing type-punned pointer will break strict-aliasing rules
htp_content_handlers.c: In function 'htp_ch_urlencoded_callback_request_line':
htp_content_handlers.c:152: warning: dereferencing type-punned pointer will break strict-aliasing rules

My attempts to understand this code have failed so I am not able to provide a patch I am confident is doing the right thing. There are about a dozen different places where this happens.

I can use -fno-strict-aliasing when building but there is one other problem:

cc1: warnings being treated as errors
htp_transcode.c: In function 'htp_transcode_bstr':
htp_transcode.c:163: warning: passing argument 2 of 'libiconv' from incompatible pointer type

Unfortunately I'm not going to have much time to devote to this for a few weeks but I can provide access to a FreeBSD machine which exhibits this behavior if necessary.

**Comment by ivanr** [comment]
Fixed.
