### ISSUE TITLE
HTP_AUTH_UNRECOGNIZED for Bearer tokens

### ISSUE THREAD

**Issue by chrislujan** [OISF/libhtp#324]
https://github.com/OISF/libhtp/blob/9cce4fb5348027fe666f21beeb829324a3afe79a/htp/htp_parsers.c#L178

This will flag the authorization header as HTP_AUTH_UNRECOGNIZED for Bearer tokens. Would it make sense to add 'bearer' as a type?

**Comment by catenacyber** [comment]
I think it would make sense indeed.
Do you want to propose a Pull Request about it ?

**Comment by chrislujan** [comment]
yeah I can push something up quickly but this would be my first commit here so bear with me as I learn the convention.

**Comment by catenacyber** [comment]
Thanks, waiting for your first PR then :-)

**Comment by chrislujan** [comment]
I'm not seeing any documentation on contribution guidelines and don't have access rights to submit a branch, could you point me in the right direction?

**Comment by catenacyber** [comment]
> don't have access rights to submit a branch

You should fork this repository, and then create a Pull Request from your repository to this one

> I'm not seeing any documentation on contribution guidelines

You can check the ones about suricata

**Comment by chrislujan** [comment]
Thanks for the info! https://github.com/OISF/libhtp/pull/325

**Comment by catenacyber** [comment]
Fixed by https://github.com/OISF/libhtp/pull/393
