### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by wxsBSD** [OISF/libhtp#35]
Is there going to be a new release? The last release was 7 months ago and that branch is woefully behind master. I maintain the FreeBSD port of libhtp and tagging releases makes it much easier on me to keep the port updated.

**Comment by ivanr** [comment]
Yes, there is going to be a new release (0.5), but it is not ready just yet. At this point I am working on the last major task, which is the cleanup of multipart parsing. The target for 0.5 is late February.
