### ISSUE TITLE
may crash

### ISSUE THREAD

**Issue by lrn0409** [OISF/libhtp#368]
function:htp_parse_authorization_basic 
after "bstr_free(connp->in_tx->request_auth_username);" need to add "connp->in_tx->request_auth_username == NULL;"
Otherwise, it may cause crash

**Comment by catenacyber** [comment]
Should this be solved by https://github.com/OISF/libhtp/pull/367 ?

**Comment by catenacyber** [comment]
Let's continue discussion in PR if needed
