### ISSUE TITLE
The post request cannot be ended when use filesotre in suricata

### ISSUE THREAD

**Issue by InterNALXz** [OISF/libhtp#377]
When i use filestore in suricata, http protocol's Get req file is saved,ftp download or upload is right. But http post cannot save file because of is not end. when i kill a sigint ,it saved. I notice the func: htp_table_get_c(rh, "content-length") return NULL and the list current size is 0. It is a BUG?

**Comment by InterNALXz** [comment]
My team built a http server with flask, and found twice 100 continue req, then got wrong by function htp_connp_RES_BODY_DETERMINE's have seen 100-Continue. So post cannot get end, and Suricata couldn't store file. The twice 100-continue is a right status?

**Comment by catenacyber** [comment]
Thanks for this report.

Would you be able to share a pcap ?
And if possible describe the expected output as a suricata-verify test ? cf https://github.com/OISF/suricata-verify/

**Comment by InterNALXz** [comment]
[http_crul_by.zip](https://github.com/OISF/libhtp/files/10997049/http_crul_by.zip)

**Comment by catenacyber** [comment]
Thanks for the pcap

Does #380 fix your problem ?

**Comment by InterNALXz** [comment]
There is also the issue of not supporting UTF-8, which is replaced with a question mark when using Chinese, whether a macro should be added to the htp_utf8_decode_path_inplace in the htp_util.c file

**Comment by InterNALXz** [comment]
> Thanks for the pcap
> 
> Does #380 fix your problem ?

is fixed

**Comment by catenacyber** [comment]
> There is also the issue of not supporting UTF-8, which is replaced with a question mark when using Chinese, whether a macro should be added to the htp_utf8_decode_path_inplace in the htp_util.c file

Ok, if this is solved, could you open another issue describing the issue about UTF-8 ?
