### ISSUE TITLE
no interface for htp_time_t

### ISSUE THREAD

**Issue by jkl-caliber** [OISF/libhtp#39]
There are no functions for working with the htp_time_t type, as far as I can tell. Also, I don't see any comment near the typedef guaranteeing that the type will always be equivalent to struct timeval.

So what is the correct way to work with values of this type?

**Comment by ivanr** [comment]
It's something I have not yet looked at. LibHTP does not use the time information right now, and thus it is there only to pass back to the callbacks. There are no plans to change the type in 0.5.x -- which is what you should be using now. It may change in one of the subsequent versions leading to 1.0, though.

I will have a look what others are doing in this area.

**Comment by ivanr** [comment]
In 0.6.x, LibHTP is now using struct timeval directly.
