### ISSUE TITLE
0.5.x: errors in htp_connp_close during CONNECT transactions

### ISSUE THREAD

**Issue by nickfajones** [OISF/libhtp#48]
The transaction state model doesn't seem to be able to handle either client or server closures and the call to htp_connp_close during CONNECT transactions.

When htp_connp_close is called, the notion of HTP_STREAM_CLOSED gets lost as final calls to htp_connp_req_data and htp_connp_res_data are made with NULL data.

The particular error I am seeing is like this:
1) htp_connp_res_data(..., NULL, 0) called
2) connp->out_state is htp_connp_RES_FINALIZE, which gets called and in turn calls htp_tx_state_response_complete_ex
3) response body data callback may be called with NULL, 0, and response complete callback may also be called, htp_tx_finalize will be called which will destroy the transaction if auto_destroy is enabled, connp->out_tx set to NULL
4) state is set to htp_connp_RES_IDLE and HTP_OK is returned
5) htp_connp_RES_IDLE is called but because input buffer is empty, HTP_DATA is returned
6) because HTP_DATA was the last return value, htp_connp_res_receiver_send_data is called, which calls the most recent data reciever hook, which in most cases for me is the response_header_data hook.
7) the hook gets invoked but it is meaningless because connp->out_tx has already been nullified.

It seems that the case of HTP_STREAM_CLOSED needs to be handled with special care in htp_connp_req/res_data to avoid the state model simply going on as if it's business as usual.

To prepare for this fix, I suggest the following changes:

```
diff -ur libhtp-0.5.4.orig/htp/htp_response.c libhtp-0.5.4/htp/htp_response.c
--- libhtp-0.5.4.orig/htp/htp_response.c    2013-07-22 09:53:21.393720488 +0000
+++ libhtp-0.5.4/htp/htp_response.c 2013-07-22 14:16:38.871365447 +0000
@@ -471,7 +471,11 @@
                 && (connp->out_tx->response_status_number <= 299)) {
             // This is a successful CONNECT stream, which means
             // we need to switch into tunneling mode.
+            connp->out_tx->response_progress = HTP_RESPONSE_COMPLETE;
+            connp->out_tx->response_transfer_coding = HTP_CODING_NO_BODY;
+
             connp->in_status = HTP_STREAM_TUNNEL;
+            connp->in_state = htp_connp_REQ_FINALIZE;
             connp->out_status = HTP_STREAM_TUNNEL;
             connp->out_state = htp_connp_RES_FINALIZE;
             return HTP_OK;
```

But I am unsure how to approach the rest.

**Comment by ivanr** [comment]
The current behaviour may not be optimal (and I will look into how I can improve it), but I am not seeing what you are describing. When connp->out_status is set to HTP_STREAM_TUNNEL and the state returns HTP_OK, processing stops and htp_connp_RES_FINALIZE is never invoked. Further invocations of htp_connp_res_data() return with HTP_STREAM_TUNNEL.

Could you supply a test case that works in the way you describe? BTW, if you compile LibHTP with --enable-debug, you should be able to trace the states as parsing is progressing. For example:

```
$ ./test/test_all.exe --gtest_filter=ConnectionParsing.SuccessfulConnectRequest
```

Perhaps the problem you are experiencing is that the transaction that establishes the tunnel is never finalized properly? (Which I think should be happening, but isn't at the moment.)

**Comment by ivanr** [comment]
Nick, I cannot reproduce this problem as described. Could you please supply a test case? Thanks.

**Comment by ivanr** [comment]
Could not reproduce.
