### ISSUE TITLE
Do not error out on newlines after response body

### ISSUE THREAD

**Issue by ivanr** [OISF/libhtp#50]
Nick Jones writes:

The worlds favourite AntiVirus test pattern, at: http://www.eicar.org/download/eicar.com (et al), actually returns an invalid http response.  It claims that the content-length is 68 bytes, but after the 68 bytes of the AV test pattern, it returns an additional two '\n' characters.

This makes libhtp-0.5.6 fail, claiming a 'response without request'.

Strictly speaking, I should limit the input that I feed to libhtp to the exact number of bytes described in the content-length field, then when the server closes the connection (which it does explicitly at the same time providing a Connection: close header), but this will not do in cases where requests are pipelined, the next 'response' would be prepended with the two '\n'.

Is there a standard way a proxy should treat this extra information, is there an rfc standard explanation for this extra information and is it a phenomenon that libhtp should handle?

**Comment by ivanr** [comment]
To fix this issue, two changes need to be made: 1) ignore newlines before new responses and 2) do not process any response data unless a request has been made.

**Comment by inliniac** [comment]
Although 2) can conflict with #53 I think?
