### ISSUE TITLE
Incomplete uninstall on OpenBSD

### ISSUE THREAD

**Issue by regit** [OISF/libhtp#51]
On libhtp-0.5.x, the uninstall Makefile target is incomplete on OpenBSD:

``` shell
# make uninstall
Making uninstall in htp
 /bin/sh ../libtool   --mode=uninstall rm -f '/usr/local/lib/libhtp.la'
```

I've tried different versions of autotools on OpenBSD with comparable results. The .so files remain on the filesystem.

It works well on Linux where lihtp*so files are removed.

**Comment by ivanr** [comment]
Thanks for reporting this problem. It's likely that I will need some time to troubleshoot this, given that I will need to build an OpenBSD virtual image beforehand (and, generally, find my way on OpenBSD). I'll study some other packages (that uninstall correctly) in order to determine what is wrong.

What OpenBSD version are you running?

**Comment by regit** [comment]
This is an OpenBSD 5.2. I've tried to look at what could be wrong in libhtp but I did not find anything obvious...

**Comment by catenacyber** [comment]
ping @regit is this still the case ?

**Comment by regit** [comment]
Did not get a look at that since a few years and I don't have anymore an Openbsd to test.

**Comment by victorjulien** [comment]
@ffontaine you are working with OpenBSD, right? Any chance you can have a look at this issue?

**Comment by ffontaine** [comment]
Nope sorry, I have no experience with OpenBSD. I'm working with buildroot (and we don't manage uninstall of packages)

**Comment by victorjulien** [comment]
> Nope sorry, I have no experience with OpenBSD. I'm working with buildroot (and we don't manage uninstall of packages)

Gotcha, thanks!

**Comment by catenacyber** [comment]
Should we close this ?
