### ISSUE TITLE
Overhaul logging and event handling

### ISSUE THREAD

**Issue by ivanr** [OISF/libhtp#61]
Implementation plan: https://github.com/ironbee/libhtp/wiki/Error-logging-in-0.6.x

**Comment by ivanr** [comment]
Updated the implementation plan.

**Comment by inliniac** [comment]
I think it looks good overall.

I think it would be nice to have a error code to string facility for the reporting side.

Also, I wonder if it would be useful to make warnings >0 and errors <0 so that the calling code can easily distinguish?

**Comment by ivanr** [comment]
An htp_log_t instance carries more data than the error code; I've made a note to add a function that produces a message from all of the available data.

As for the warnings/error question: you already have the log level that you can use for this purpose:

```
enum htp_log_level_t {
HTP_LOG_NONE = 0,
HTP_LOG_ERROR = 1,
HTP_LOG_WARNING = 2,
HTP_LOG_NOTICE = 3,
HTP_LOG_INFO = 4,
HTP_LOG_DEBUG = 5,
HTP_LOG_DEBUG2 = 6
};
```

**Comment by catenacyber** [comment]
Closing this old issue as it seems to big a cya,he for libhtp currently...
Next big project is switching to rust
