### ISSUE TITLE
Implement parsing without data copying wherever possible

### ISSUE THREAD

**Issue by ivanr** [OISF/libhtp#8]

**Comment by b1v1r** [comment]
An enhancement to bstr that allows aliasing memory + length would help here.  For example, be able to mark the first 4 bytes of the raw header as the header name.  Not always possible due to transformations, etc

**Comment by ivanr** [comment]
The key issue here is the expectation of how long certain pieces of data are going to be available. We can implement a fully streaming parser, but that's only useful to a fully streaming consumer. We should start by not having 2 copies of message headers.

**Comment by ivanr** [comment]
Removing enhancements from the issue tracker.

**Comment by ivanr** [comment]
Implemented in master.
