### ISSUE TITLE
Problems with including config.h in htp_private.h

### ISSUE THREAD

**Issue by b1v1r** [OISF/libhtp#99]
79c2e9e2decf41fbebdc4d99fb6c485b9974e2bd broke being able to include htp_private.h in another product. Yes, we should not be doing this, but there is not a way to look at htp_cfg_t otherwise. This structure was made private, but there are no accessors (only setters) that are public.

It is a really bad idea to include the autoconf header in another header as the config.h has no include guards and uses too many generic names that will conflict (e.g., VERSION). The config.h is mean to ONLY be included from a source file and not another header. 

Please consider reverting 79c2e9e2decf41fbebdc4d99fb6c485b9974e2bd. I have done so in ironbee codebase until other issues surrounding private structures can be resolved.

**Comment by catenacyber** [comment]
Looks fixed by #101
